import type { Metadata } from 'next';
import './globals.css';

import Header from '@/components/commom/header';
import { SVNGilroy } from '@/theme/fonts';
import { ThemeProvider } from '@/theme/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${SVNGilroy.className} ${SVNGilroy.variable} antialiased w-screen h-screen`}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system" disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
