import type { Metadata } from 'next';
import './globals.css';

import Header from '@/components/commom/header';
import { Toaster } from '@/components/ui/sonner';
import { AppProvider } from '@/contexts/app-ctx';
import { SVNGilroy } from '@/theme/fonts';
import { ThemeProvider } from '@/theme/provider';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${SVNGilroy.className} ${SVNGilroy.variable} antialiased w-screen h-screen`}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system" disableTransitionOnChange>
          <Header />
          <AppProvider token={cookieStore.get('sessionToken')?.value}>{children}</AppProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
